name: Build Linux Image

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    
    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get install build-essential subversion git-core libncurses5-dev zlib1g-dev gawk flex quilt libssl-dev xsltproc libxml-parser-perl \
          mercurial bzr ecj cvs unzip lib32z1 lib32z1-dev lib32stdc++6 libstdc++6 libmpc-dev libgmp-dev -y
          
    - name: Update submodules
      run: git submodule update --init --recursive
      
    - name: Cache downloads
      id: cache-downloads
      uses: actions/cache@v3
      env:
        cache-name: cache-downloaded-files
      with:
        path: |
          prebuilt.tar.gz
          dl.tar
          lichee/brandy-2.0/tools/toolchain/riscv64-linux-x86_64-20200528.tar.xz
          lichee/brandy-2.0/tools/toolchain/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabi.tar.xz
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        
    - if: ${{ steps.cache-downloads.outputs.cache-hit != 'true' }}
      name: Download requirements
      run: |
        wget -nv http://89.208.105.226:8080/temporary/riscv64-linux-x86_64-20200528.tar.xz -P ./lichee/brandy-2.0/tools/toolchain/
        wget -nv http://89.208.105.226:8080/temporary/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabi.tar.xz -P ./lichee/brandy-2.0/tools/toolchain/
        wget -nv http://89.208.105.226:8080/temporary/prebuilt.tar.gz && tar xzf prebuilt.tar.gz
        wget -nv http://89.208.105.226:8080/temporary/dl.tar && tar xf dl.tar
#        wget -nv http://dl.mangopi.cc/tina/prebuilt.tar.gz . && tar xzf prebuilt.tar.gz
#        wget -nv http://dl.mangopi.cc/tina/dl.tar . && tar xf dl.tar
#        wget -nv http://dl.mangopi.cc/tina/toolchain/riscv64-linux-x86_64-20200528.tar.xz -P ./lichee/brandy-2.0/tools/toolchain/
#        wget -nv http://dl.mangopi.cc/tina/toolchain/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabi.tar.xz -P ./lichee/brandy-2.0/tools/toolchain/
        
    - name: Configure and make
      run: (source build/envsetup.sh && lunch 5 && make && mboot && pack) || true
      
    - name: Enviroment set
      run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          
    - name: Upload result as release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "Tina-Linux/out/**/tina_*.img"
#        body: ""
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.TAG_NAME }}
        name: ${{ env.RELEASE_NAME }}
  
